language: ruby

dist: trusty

rvm:
  - 1.8.7
  - 2.1.8
  - 2.3.1
  - 2.4.2
  - 2.5.3

gemfile:
  - Gemfile.2.3
  - Gemfile.3.2
  - Gemfile.4.2
  - Gemfile.5.0
  - Gemfile.5.1
  - Gemfile.5.1.pg
  - Gemfile.6.0.pg

matrix:
  exclude:
    - gemfile: Gemfile.2.3
      rvm: 2.1.8
    - gemfile: Gemfile.2.3
      rvm: 2.3.1
    - gemfile: Gemfile.2.3
      rvm: 2.4.2
    - gemfile: Gemfile.2.3
      rvm: 2.5.3
    - gemfile: Gemfile.3.2
      rvm: 2.3.1
    - gemfile: Gemfile.3.2
      rvm: 2.4.2
    - gemfile: Gemfile.3.2
      rvm: 2.5.3
    - gemfile: Gemfile.4.2
      rvm: 1.8.7
    - gemfile: Gemfile.4.2
      rvm: 2.4.2
    - gemfile: Gemfile.4.2
      rvm: 2.5.3
    - gemfile: Gemfile.5.0
      rvm: 1.8.7
    - gemfile: Gemfile.5.0
      rvm: 2.1.8
    - gemfile: Gemfile.5.1
      rvm: 1.8.7
    - gemfile: Gemfile.5.1
      rvm: 2.1.8
    - gemfile: Gemfile.5.1.pg
      rvm: 1.8.7
    - gemfile: Gemfile.5.1.pg
      rvm: 2.1.8
    - gemfile: Gemfile.6.0.pg
      rvm: 1.8.7
    - gemfile: Gemfile.6.0.pg
      rvm: 2.1.8
    - gemfile: Gemfile.6.0.pg
      rvm: 2.3.1
    - gemfile: Gemfile.6.0.pg
      rvm: 2.4.2

addons:
    postgresql: "9.4"

sudo: false

cache: bundler

before_script:
  - psql -c 'create database assignable_values_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS assignable_values_test;'

install:
  # Old Travis CI bundler explodes when lockfile version doesn't match recently bumped version
  - gem install bundler --version='=1.12.5'
  # This is the default Travis CI install step
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec rake current_rspec
