language: ruby

rvm:
  - 1.8.7
  - 2.1.8
  - 2.3.1

gemfile:
  - gemfiles/Gemfile.2.3
  - gemfiles/Gemfile.3.2
  - gemfiles/Gemfile.4.2
  - gemfiles/Gemfile.5.0
  - gemfiles/Gemfile.5.1

matrix:
  exclude:
    - gemfile: gemfiles/Gemfile.2.3
      rvm: 2.1.8
    - gemfile: gemfiles/Gemfile.2.3
      rvm: 2.3.1
    - gemfile: gemfiles/Gemfile.3.2
      rvm: 2.3.1
    - gemfile: gemfiles/Gemfile.4.2
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.5.0
      rvm: 2.1.8
    - gemfile: gemfiles/Gemfile.5.0
      rvm: 1.8.7
    - gemfile: gemfiles/Gemfile.5.1
      rvm: 2.1.8
    - gemfile: gemfiles/Gemfile.5.1
      rvm: 1.8.7

sudo: false

cache: bundler

notifications:
  email:
    - fail@makandra.de

before_script:
  - mysql -e 'create database IF NOT EXISTS assignable_values_test;'
  - mysql -e "GRANT ALL PRIVILEGES ON assignable_values_test.* TO 'travis'@'%';"

install:
  # Old Travis CI bundler explodes when lockfile version doesn't match recently bumped version
  - gem install bundler --version='=1.12.5'
  # This is the default Travis CI install step
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec rake current_rspec
