language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.1.0"
  - ree
services:
  - mysql
script: rake travis:run
notifications:
  email:
    - fail@makandra.de
branches:
  only:
    - master
    - travis-testing
